# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0008_auto_20160109_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='url',
            field=models.URLField(default='https://www.com', help_text='Brewery site url'),
            preserve_default=False,
        ),
    ]
